import React from 'react'

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

// export const metadata = {
//   title: 'Home',
//   description: "Generated by create next app",
// };
const Home = async () => {
  // await delay(2000) // just for testing

  return (
    <>
      Home
    </>
  )
}

export default Home