import React from 'react'

// export const metadata = {
//   title: 'Home',
//   description: "Generated by create next app",
// };
const Home = () => {
  return (
    <>Home
    </>
  )
}

export default Home